/**
* This file is auto-generated by @svgr-iconkit/cli
* Do not edit this file manually.
* Update the icons definition in the source file and run the command to regenerate this file.
*/
import { IconsMapType } from "@svgr-iconkit/core";

// import assets
import SVG_archive from "./archive";
import SVG_arrowDown from "./arrow-down";
import SVG_arrowLeft from "./arrow-left";
import SVG_arrowRight from "./arrow-right";
import SVG_arrowUp from "./arrow-up";
import SVG_bell from "./bell";
import SVG_calendar from "./calendar";
import SVG_camera from "./camera";
import SVG_cart from "./cart";
import SVG_chart from "./chart";
import SVG_check from "./check";
import SVG_chevronDown from "./chevron-down";
import SVG_chevronLeft from "./chevron-left";
import SVG_chevronRight from "./chevron-right";
import SVG_chevronUp from "./chevron-up";
import SVG_clock from "./clock";
import SVG_closeO from "./close-o";
import SVG_close from "./close";
import SVG_comment from "./comment";
import SVG_creditCard from "./credit-card";
import SVG_envelope from "./envelope";
import SVG_exclamation from "./exclamation";
import SVG_externalLink from "./external-link";
import SVG_eye from "./eye";
import SVG_gear from "./gear";
import SVG_heart from "./heart";
import SVG_image from "./image";
import SVG_like from "./like";
import SVG_link from "./link";
import SVG_location from "./location";
import SVG_lock from "./lock";
import SVG_minus from "./minus";
import SVG_navicon from "./navicon";
import SVG_paperclip from "./paperclip";
import SVG_pencil from "./pencil";
import SVG_play from "./play";
import SVG_plus from "./plus";
import SVG_pointer from "./pointer";
import SVG_question from "./question";
import SVG_redo from "./redo";
import SVG_refresh from "./refresh";
import SVG_retweet from "./retweet";
import SVG_scFacebook from "./sc-facebook";
import SVG_scGithub from "./sc-github";
import SVG_scGooglePlus from "./sc-google-plus";
import SVG_scInstagram from "./sc-instagram";
import SVG_scLinkedin from "./sc-linkedin";
import SVG_scOdnoklassniki from "./sc-odnoklassniki";
import SVG_scPinterest from "./sc-pinterest";
import SVG_scSkype from "./sc-skype";
import SVG_scSoundcloud from "./sc-soundcloud";
import SVG_scTelegram from "./sc-telegram";
import SVG_scTumblr from "./sc-tumblr";
import SVG_scTwitter from "./sc-twitter";
import SVG_scVimeo from "./sc-vimeo";
import SVG_scVk from "./sc-vk";
import SVG_scYoutube from "./sc-youtube";
import SVG_search from "./search";
import SVG_shareApple from "./share-apple";
import SVG_shareGoogle from "./share-google";
import SVG_spinner2 from "./spinner-2";
import SVG_spinner3 from "./spinner-3";
import SVG_spinner from "./spinner";
import SVG_star from "./star";
import SVG_tag from "./tag";
import SVG_trash from "./trash";
import SVG_trophy from "./trophy";
import SVG_undo from "./undo";
import SVG_unlock from "./unlock";
import SVG_user from "./user"

// map
const contentMap = {
"archive": SVG_archive,
"arrow-down": SVG_arrowDown,
"arrow-left": SVG_arrowLeft,
"arrow-right": SVG_arrowRight,
"arrow-up": SVG_arrowUp,
"bell": SVG_bell,
"calendar": SVG_calendar,
"camera": SVG_camera,
"cart": SVG_cart,
"chart": SVG_chart,
"check": SVG_check,
"chevron-down": SVG_chevronDown,
"chevron-left": SVG_chevronLeft,
"chevron-right": SVG_chevronRight,
"chevron-up": SVG_chevronUp,
"clock": SVG_clock,
"close-o": SVG_closeO,
"close": SVG_close,
"comment": SVG_comment,
"credit-card": SVG_creditCard,
"envelope": SVG_envelope,
"exclamation": SVG_exclamation,
"external-link": SVG_externalLink,
"eye": SVG_eye,
"gear": SVG_gear,
"heart": SVG_heart,
"image": SVG_image,
"like": SVG_like,
"link": SVG_link,
"location": SVG_location,
"lock": SVG_lock,
"minus": SVG_minus,
"navicon": SVG_navicon,
"paperclip": SVG_paperclip,
"pencil": SVG_pencil,
"play": SVG_play,
"plus": SVG_plus,
"pointer": SVG_pointer,
"question": SVG_question,
"redo": SVG_redo,
"refresh": SVG_refresh,
"retweet": SVG_retweet,
"sc-facebook": SVG_scFacebook,
"sc-github": SVG_scGithub,
"sc-google-plus": SVG_scGooglePlus,
"sc-instagram": SVG_scInstagram,
"sc-linkedin": SVG_scLinkedin,
"sc-odnoklassniki": SVG_scOdnoklassniki,
"sc-pinterest": SVG_scPinterest,
"sc-skype": SVG_scSkype,
"sc-soundcloud": SVG_scSoundcloud,
"sc-telegram": SVG_scTelegram,
"sc-tumblr": SVG_scTumblr,
"sc-twitter": SVG_scTwitter,
"sc-vimeo": SVG_scVimeo,
"sc-vk": SVG_scVk,
"sc-youtube": SVG_scYoutube,
"search": SVG_search,
"share-apple": SVG_shareApple,
"share-google": SVG_shareGoogle,
"spinner-2": SVG_spinner2,
"spinner-3": SVG_spinner3,
"spinner": SVG_spinner,
"star": SVG_star,
"tag": SVG_tag,
"trash": SVG_trash,
"trophy": SVG_trophy,
"undo": SVG_undo,
"unlock": SVG_unlock,
"user": SVG_user
};

// types
export type IconNames = keyof typeof contentMap;

// iconNames
export const iconNames: IconNames[] = Object.keys(contentMap) as IconNames[];

export const map: IconsMapType<IconNames> = contentMap;
