/**
* This file is auto-generated by @svgr-iconkit/cli
* Do not edit this file manually.
* Update the icons definition in the source file and run the command to regenerate this file.
*/
import { IconsMapType } from "@svgr-iconkit/core";

// import assets
import SVG_0Circle from "./0-circle";
import SVG_0Square from "./0-square";
import SVG_1Circle from "./1-circle";
import SVG_1Square from "./1-square";
import SVG_2Circle from "./2-circle";
import SVG_2Square from "./2-square";
import SVG_3Circle from "./3-circle";
import SVG_3Square from "./3-square";
import SVG_4Circle from "./4-circle";
import SVG_4Square from "./4-square";
import SVG_5Circle from "./5-circle";
import SVG_5Square from "./5-square";
import SVG_6Circle from "./6-circle";
import SVG_6Square from "./6-square";
import SVG_7Circle from "./7-circle";
import SVG_7Square from "./7-square";
import SVG_8Circle from "./8-circle";
import SVG_8Square from "./8-square";
import SVG_9Circle from "./9-circle";
import SVG_9Square from "./9-square";
import SVG_airplaneEngines from "./airplane-engines";
import SVG_airplane from "./airplane";
import SVG_alarm from "./alarm";
import SVG_archive from "./archive";
import SVG_arrowDownCircle from "./arrow-down-circle";
import SVG_arrowDownLeftCircle from "./arrow-down-left-circle";
import SVG_arrowDownLeftSquare from "./arrow-down-left-square";
import SVG_arrowDownRightCircle from "./arrow-down-right-circle";
import SVG_arrowDownRightSquare from "./arrow-down-right-square";
import SVG_arrowDownSquare from "./arrow-down-square";
import SVG_arrowLeftCircle from "./arrow-left-circle";
import SVG_arrowLeftSquare from "./arrow-left-square";
import SVG_arrowRightCircle from "./arrow-right-circle";
import SVG_arrowRightSquare from "./arrow-right-square";
import SVG_arrowThroughHeart from "./arrow-through-heart";
import SVG_arrowUpCircle from "./arrow-up-circle";
import SVG_arrowUpLeftCircle from "./arrow-up-left-circle";
import SVG_arrowUpLeftSquare from "./arrow-up-left-square";
import SVG_arrowUpRightCircle from "./arrow-up-right-circle";
import SVG_arrowUpRightSquare from "./arrow-up-right-square";
import SVG_arrowUpSquare from "./arrow-up-square";
import SVG_aspectRatio from "./aspect-ratio";
import SVG_award from "./award";
import SVG_backpack from "./backpack";
import SVG_backpack2 from "./backpack2";
import SVG_backpack3 from "./backpack3";
import SVG_backpack4 from "./backpack4";
import SVG_backspace from "./backspace";
import SVG_backspaceReverse from "./backspace-reverse";
import SVG_badge3d from "./badge-3d";
import SVG_badge4k from "./badge-4k";
import SVG_badge8k from "./badge-8k";
import SVG_badgeAd from "./badge-ad";
import SVG_badgeAr from "./badge-ar";
import SVG_badgeCc from "./badge-cc";
import SVG_badgeHd from "./badge-hd";
import SVG_badgeSd from "./badge-sd";
import SVG_badgeTm from "./badge-tm";
import SVG_badgeVo from "./badge-vo";
import SVG_badgeVr from "./badge-vr";
import SVG_badgeWc from "./badge-wc";
import SVG_bagCheck from "./bag-check";
import SVG_bagDash from "./bag-dash";
import SVG_bag from "./bag";
import SVG_bagHeart from "./bag-heart";
import SVG_bagPlus from "./bag-plus";
import SVG_bagX from "./bag-x";
import SVG_balloon from "./balloon";
import SVG_balloonHeart from "./balloon-heart";
import SVG_ban from "./ban";
import SVG_bandaid from "./bandaid";
import SVG_barChart from "./bar-chart";
import SVG_barChartLine from "./bar-chart-line";
import SVG_basket from "./basket";
import SVG_basket2 from "./basket2";
import SVG_basket3 from "./basket3";
import SVG_bell from "./bell";
import SVG_bellSlash from "./bell-slash";
import SVG_binoculars from "./binoculars";
import SVG_book from "./book";
import SVG_bookmarkCheck from "./bookmark-check";
import SVG_bookmarkDash from "./bookmark-dash";
import SVG_bookmark from "./bookmark";
import SVG_bookmarkHeart from "./bookmark-heart";
import SVG_bookmarkPlus from "./bookmark-plus";
import SVG_bookmarkStar from "./bookmark-star";
import SVG_bookmarkX from "./bookmark-x";
import SVG_bookmarks from "./bookmarks";
import SVG_boombox from "./boombox";
import SVG_bootstrap from "./bootstrap";
import SVG_box from "./box";
import SVG_boxSeam from "./box-seam";
import SVG_box2 from "./box2";
import SVG_box2Heart from "./box2-heart";
import SVG_briefcase from "./briefcase";
import SVG_brightnessAltHigh from "./brightness-alt-high";
import SVG_brightnessAltLow from "./brightness-alt-low";
import SVG_brightnessHigh from "./brightness-high";
import SVG_brightnessLow from "./brightness-low";
import SVG_brush from "./brush";
import SVG_bucket from "./bucket";
import SVG_bug from "./bug";
import SVG_building from "./building";
import SVG_buildings from "./buildings";
import SVG_busFront from "./bus-front";
import SVG_cCircle from "./c-circle";
import SVG_cSquare from "./c-square";
import SVG_cake from "./cake";
import SVG_cake2 from "./cake2";
import SVG_calculator from "./calculator";
import SVG_calendarCheck from "./calendar-check";
import SVG_calendarDate from "./calendar-date";
import SVG_calendarDay from "./calendar-day";
import SVG_calendarEvent from "./calendar-event";
import SVG_calendar from "./calendar";
import SVG_calendarHeart from "./calendar-heart";
import SVG_calendarMinus from "./calendar-minus";
import SVG_calendarMonth from "./calendar-month";
import SVG_calendarPlus from "./calendar-plus";
import SVG_calendarRange from "./calendar-range";
import SVG_calendarWeek from "./calendar-week";
import SVG_calendarX from "./calendar-x";
import SVG_calendar2Check from "./calendar2-check";
import SVG_calendar2Date from "./calendar2-date";
import SVG_calendar2Day from "./calendar2-day";
import SVG_calendar2Event from "./calendar2-event";
import SVG_calendar2 from "./calendar2";
import SVG_calendar2Heart from "./calendar2-heart";
import SVG_calendar2Minus from "./calendar2-minus";
import SVG_calendar2Month from "./calendar2-month";
import SVG_calendar2Plus from "./calendar2-plus";
import SVG_calendar2Range from "./calendar2-range";
import SVG_calendar2Week from "./calendar2-week";
import SVG_calendar2X from "./calendar2-x";
import SVG_calendar3Event from "./calendar3-event";
import SVG_calendar3 from "./calendar3";
import SVG_calendar3Range from "./calendar3-range";
import SVG_calendar3Week from "./calendar3-week";
import SVG_camera from "./camera";
import SVG_cameraReels from "./camera-reels";
import SVG_cameraVideo from "./camera-video";
import SVG_cameraVideoOff from "./camera-video-off";
import SVG_capslock from "./capslock";
import SVG_carFront from "./car-front";
import SVG_caretDown from "./caret-down";
import SVG_caretDownSquare from "./caret-down-square";
import SVG_caretLeft from "./caret-left";
import SVG_caretLeftSquare from "./caret-left-square";
import SVG_caretRight from "./caret-right";
import SVG_caretRightSquare from "./caret-right-square";
import SVG_caretUp from "./caret-up";
import SVG_caretUpSquare from "./caret-up-square";
import SVG_cartCheck from "./cart-check";
import SVG_cartDash from "./cart-dash";
import SVG_cart from "./cart";
import SVG_cartPlus from "./cart-plus";
import SVG_cartX from "./cart-x";
import SVG_cassette from "./cassette";
import SVG_ccCircle from "./cc-circle";
import SVG_ccSquare from "./cc-square";
import SVG_chatDots from "./chat-dots";
import SVG_chat from "./chat";
import SVG_chatHeart from "./chat-heart";
import SVG_chatLeftDots from "./chat-left-dots";
import SVG_chatLeft from "./chat-left";
import SVG_chatLeftHeart from "./chat-left-heart";
import SVG_chatLeftQuote from "./chat-left-quote";
import SVG_chatLeftText from "./chat-left-text";
import SVG_chatQuote from "./chat-quote";
import SVG_chatRightDots from "./chat-right-dots";
import SVG_chatRight from "./chat-right";
import SVG_chatRightHeart from "./chat-right-heart";
import SVG_chatRightQuote from "./chat-right-quote";
import SVG_chatRightText from "./chat-right-text";
import SVG_chatSquareDots from "./chat-square-dots";
import SVG_chatSquare from "./chat-square";
import SVG_chatSquareHeart from "./chat-square-heart";
import SVG_chatSquareQuote from "./chat-square-quote";
import SVG_chatSquareText from "./chat-square-text";
import SVG_chatText from "./chat-text";
import SVG_checkCircle from "./check-circle";
import SVG_checkSquare from "./check-square";
import SVG_circle from "./circle";
import SVG_clipboardCheck from "./clipboard-check";
import SVG_clipboardData from "./clipboard-data";
import SVG_clipboard from "./clipboard";
import SVG_clipboardHeart from "./clipboard-heart";
import SVG_clipboardMinus from "./clipboard-minus";
import SVG_clipboardPlus from "./clipboard-plus";
import SVG_clipboardX from "./clipboard-x";
import SVG_clipboard2Check from "./clipboard2-check";
import SVG_clipboard2Data from "./clipboard2-data";
import SVG_clipboard2 from "./clipboard2";
import SVG_clipboard2Heart from "./clipboard2-heart";
import SVG_clipboard2Minus from "./clipboard2-minus";
import SVG_clipboard2Plus from "./clipboard2-plus";
import SVG_clipboard2Pulse from "./clipboard2-pulse";
import SVG_clipboard2X from "./clipboard2-x";
import SVG_clock from "./clock";
import SVG_cloudArrowDown from "./cloud-arrow-down";
import SVG_cloudArrowUp from "./cloud-arrow-up";
import SVG_cloudCheck from "./cloud-check";
import SVG_cloudDownload from "./cloud-download";
import SVG_cloudDrizzle from "./cloud-drizzle";
import SVG_cloud from "./cloud";
import SVG_cloudFog from "./cloud-fog";
import SVG_cloudFog2 from "./cloud-fog2";
import SVG_cloudHail from "./cloud-hail";
import SVG_cloudHaze from "./cloud-haze";
import SVG_cloudHaze2 from "./cloud-haze2";
import SVG_cloudLightning from "./cloud-lightning";
import SVG_cloudLightningRain from "./cloud-lightning-rain";
import SVG_cloudMinus from "./cloud-minus";
import SVG_cloudMoon from "./cloud-moon";
import SVG_cloudPlus from "./cloud-plus";
import SVG_cloudRain from "./cloud-rain";
import SVG_cloudRainHeavy from "./cloud-rain-heavy";
import SVG_cloudSlash from "./cloud-slash";
import SVG_cloudSleet from "./cloud-sleet";
import SVG_cloudSnow from "./cloud-snow";
import SVG_cloudSun from "./cloud-sun";
import SVG_cloudUpload from "./cloud-upload";
import SVG_clouds from "./clouds";
import SVG_cloudy from "./cloudy";
import SVG_collection from "./collection";
import SVG_collectionPlay from "./collection-play";
import SVG_compass from "./compass";
import SVG_cpu from "./cpu";
import SVG_creditCard2Back from "./credit-card-2-back";
import SVG_creditCard2Front from "./credit-card-2-front";
import SVG_creditCard from "./credit-card";
import SVG_cup from "./cup";
import SVG_cupHot from "./cup-hot";
import SVG_cursor from "./cursor";
import SVG_dashCircle from "./dash-circle";
import SVG_dashSquare from "./dash-square";
import SVG_database from "./database";
import SVG_deviceHdd from "./device-hdd";
import SVG_deviceSsd from "./device-ssd";
import SVG_diagram2 from "./diagram-2";
import SVG_diagram3 from "./diagram-3";
import SVG_diamond from "./diamond";
import SVG_dice1 from "./dice-1";
import SVG_dice2 from "./dice-2";
import SVG_dice3 from "./dice-3";
import SVG_dice4 from "./dice-4";
import SVG_dice5 from "./dice-5";
import SVG_dice6 from "./dice-6";
import SVG_disc from "./disc";
import SVG_display from "./display";
import SVG_displayport from "./displayport";
import SVG_doorClosed from "./door-closed";
import SVG_doorOpen from "./door-open";
import SVG_dpad from "./dpad";
import SVG_droplet from "./droplet";
import SVG_duffle from "./duffle";
import SVG_ear from "./ear";
import SVG_easel from "./easel";
import SVG_easel2 from "./easel2";
import SVG_easel3 from "./easel3";
import SVG_egg from "./egg";
import SVG_eject from "./eject";
import SVG_emojiAngry from "./emoji-angry";
import SVG_emojiAstonished from "./emoji-astonished";
import SVG_emojiDizzy from "./emoji-dizzy";
import SVG_emojiExpressionless from "./emoji-expressionless";
import SVG_emojiFrown from "./emoji-frown";
import SVG_emojiGrimace from "./emoji-grimace";
import SVG_emojiGrin from "./emoji-grin";
import SVG_emojiHeartEyes from "./emoji-heart-eyes";
import SVG_emojiKiss from "./emoji-kiss";
import SVG_emojiLaughing from "./emoji-laughing";
import SVG_emojiNeutral from "./emoji-neutral";
import SVG_emojiSmile from "./emoji-smile";
import SVG_emojiSmileUpsideDown from "./emoji-smile-upside-down";
import SVG_emojiSunglasses from "./emoji-sunglasses";
import SVG_emojiSurprise from "./emoji-surprise";
import SVG_emojiTear from "./emoji-tear";
import SVG_emojiWink from "./emoji-wink";
import SVG_envelopeArrowDown from "./envelope-arrow-down";
import SVG_envelopeArrowUp from "./envelope-arrow-up";
import SVG_envelopeAt from "./envelope-at";
import SVG_envelopeCheck from "./envelope-check";
import SVG_envelopeDash from "./envelope-dash";
import SVG_envelopeExclamation from "./envelope-exclamation";
import SVG_envelope from "./envelope";
import SVG_envelopeHeart from "./envelope-heart";
import SVG_envelopeOpen from "./envelope-open";
import SVG_envelopeOpenHeart from "./envelope-open-heart";
import SVG_envelopePaper from "./envelope-paper";
import SVG_envelopePaperHeart from "./envelope-paper-heart";
import SVG_envelopePlus from "./envelope-plus";
import SVG_envelopeSlash from "./envelope-slash";
import SVG_envelopeX from "./envelope-x";
import SVG_eraser from "./eraser";
import SVG_evFront from "./ev-front";
import SVG_evStation from "./ev-station";
import SVG_exclamationCircle from "./exclamation-circle";
import SVG_exclamationDiamond from "./exclamation-diamond";
import SVG_exclamationOctagon from "./exclamation-octagon";
import SVG_exclamationSquare from "./exclamation-square";
import SVG_exclamationTriangle from "./exclamation-triangle";
import SVG_explicit from "./explicit";
import SVG_eye from "./eye";
import SVG_eyeSlash from "./eye-slash";
import SVG_fastForwardBtn from "./fast-forward-btn";
import SVG_fastForwardCircle from "./fast-forward-circle";
import SVG_fastForward from "./fast-forward";
import SVG_fileArrowDown from "./file-arrow-down";
import SVG_fileArrowUp from "./file-arrow-up";
import SVG_fileBarGraph from "./file-bar-graph";
import SVG_fileBinary from "./file-binary";
import SVG_fileBreak from "./file-break";
import SVG_fileCheck from "./file-check";
import SVG_fileCode from "./file-code";
import SVG_fileDiff from "./file-diff";
import SVG_fileEarmarkArrowDown from "./file-earmark-arrow-down";
import SVG_fileEarmarkArrowUp from "./file-earmark-arrow-up";
import SVG_fileEarmarkBarGraph from "./file-earmark-bar-graph";
import SVG_fileEarmarkBinary from "./file-earmark-binary";
import SVG_fileEarmarkBreak from "./file-earmark-break";
import SVG_fileEarmarkCheck from "./file-earmark-check";
import SVG_fileEarmarkCode from "./file-earmark-code";
import SVG_fileEarmarkDiff from "./file-earmark-diff";
import SVG_fileEarmarkEasel from "./file-earmark-easel";
import SVG_fileEarmarkExcel from "./file-earmark-excel";
import SVG_fileEarmark from "./file-earmark";
import SVG_fileEarmarkFont from "./file-earmark-font";
import SVG_fileEarmarkImage from "./file-earmark-image";
import SVG_fileEarmarkLock from "./file-earmark-lock";
import SVG_fileEarmarkLock2 from "./file-earmark-lock2";
import SVG_fileEarmarkMedical from "./file-earmark-medical";
import SVG_fileEarmarkMinus from "./file-earmark-minus";
import SVG_fileEarmarkMusic from "./file-earmark-music";
import SVG_fileEarmarkPdf from "./file-earmark-pdf";
import SVG_fileEarmarkPerson from "./file-earmark-person";
import SVG_fileEarmarkPlay from "./file-earmark-play";
import SVG_fileEarmarkPlus from "./file-earmark-plus";
import SVG_fileEarmarkPost from "./file-earmark-post";
import SVG_fileEarmarkPpt from "./file-earmark-ppt";
import SVG_fileEarmarkRichtext from "./file-earmark-richtext";
import SVG_fileEarmarkRuled from "./file-earmark-ruled";
import SVG_fileEarmarkSlides from "./file-earmark-slides";
import SVG_fileEarmarkSpreadsheet from "./file-earmark-spreadsheet";
import SVG_fileEarmarkText from "./file-earmark-text";
import SVG_fileEarmarkWord from "./file-earmark-word";
import SVG_fileEarmarkX from "./file-earmark-x";
import SVG_fileEarmarkZip from "./file-earmark-zip";
import SVG_fileEasel from "./file-easel";
import SVG_fileExcel from "./file-excel";
import SVG_file from "./file";
import SVG_fileFont from "./file-font";
import SVG_fileImage from "./file-image";
import SVG_fileLock from "./file-lock";
import SVG_fileLock2 from "./file-lock2";
import SVG_fileMedical from "./file-medical";
import SVG_fileMinus from "./file-minus";
import SVG_fileMusic from "./file-music";
import SVG_filePdf from "./file-pdf";
import SVG_filePerson from "./file-person";
import SVG_filePlay from "./file-play";
import SVG_filePlus from "./file-plus";
import SVG_filePost from "./file-post";
import SVG_filePpt from "./file-ppt";
import SVG_fileRichtext from "./file-richtext";
import SVG_fileRuled from "./file-ruled";
import SVG_fileSlides from "./file-slides";
import SVG_fileSpreadsheet from "./file-spreadsheet";
import SVG_fileText from "./file-text";
import SVG_fileWord from "./file-word";
import SVG_fileX from "./file-x";
import SVG_fileZip from "./file-zip";
import SVG_filterCircle from "./filter-circle";
import SVG_filterSquare from "./filter-square";
import SVG_flag from "./flag";
import SVG_floppy from "./floppy";
import SVG_floppy2 from "./floppy2";
import SVG_folder from "./folder";
import SVG_folderSymlink from "./folder-symlink";
import SVG_forward from "./forward";
import SVG_fuelPumpDiesel from "./fuel-pump-diesel";
import SVG_fuelPump from "./fuel-pump";
import SVG_funnel from "./funnel";
import SVG_gear from "./gear";
import SVG_geoAlt from "./geo-alt";
import SVG_geo from "./geo";
import SVG_gift from "./gift";
import SVG_grid1x2 from "./grid-1x2";
import SVG_grid3x2Gap from "./grid-3x2-gap";
import SVG_grid3x3Gap from "./grid-3x3-gap";
import SVG_grid from "./grid";
import SVG_hCircle from "./h-circle";
import SVG_hSquare from "./h-square";
import SVG_handIndex from "./hand-index";
import SVG_handIndexThumb from "./hand-index-thumb";
import SVG_handThumbsDown from "./hand-thumbs-down";
import SVG_handThumbsUp from "./hand-thumbs-up";
import SVG_handbag from "./handbag";
import SVG_hdd from "./hdd";
import SVG_hddNetwork from "./hdd-network";
import SVG_hddRack from "./hdd-rack";
import SVG_hddStack from "./hdd-stack";
import SVG_hdmi from "./hdmi";
import SVG_heart from "./heart";
import SVG_heartPulse from "./heart-pulse";
import SVG_heartbreak from "./heartbreak";
import SVG_heptagon from "./heptagon";
import SVG_hexagon from "./hexagon";
import SVG_hospital from "./hospital";
import SVG_houseAdd from "./house-add";
import SVG_houseCheck from "./house-check";
import SVG_houseDash from "./house-dash";
import SVG_houseDoor from "./house-door";
import SVG_houseDown from "./house-down";
import SVG_houseExclamation from "./house-exclamation";
import SVG_house from "./house";
import SVG_houseGear from "./house-gear";
import SVG_houseHeart from "./house-heart";
import SVG_houseLock from "./house-lock";
import SVG_houseSlash from "./house-slash";
import SVG_houseUp from "./house-up";
import SVG_houseX from "./house-x";
import SVG_houses from "./houses";
import SVG_image from "./image";
import SVG_inbox from "./inbox";
import SVG_inboxes from "./inboxes";
import SVG_infoCircle from "./info-circle";
import SVG_infoSquare from "./info-square";
import SVG_journalBookmark from "./journal-bookmark";
import SVG_kanban from "./kanban";
import SVG_key from "./key";
import SVG_keyboard from "./keyboard";
import SVG_lamp from "./lamp";
import SVG_laptop from "./laptop";
import SVG_layers from "./layers";
import SVG_lightbulb from "./lightbulb";
import SVG_lightbulbOff from "./lightbulb-off";
import SVG_lightningCharge from "./lightning-charge";
import SVG_lightning from "./lightning";
import SVG_lock from "./lock";
import SVG_luggage from "./luggage";
import SVG_lungs from "./lungs";
import SVG_magnet from "./magnet";
import SVG_map from "./map";
import SVG_markdown from "./markdown";
import SVG_megaphone from "./megaphone";
import SVG_menuApp from "./menu-app";
import SVG_menuButton from "./menu-button";
import SVG_menuButtonWide from "./menu-button-wide";
import SVG_mic from "./mic";
import SVG_micMute from "./mic-mute";
import SVG_modem from "./modem";
import SVG_moon from "./moon";
import SVG_moonStars from "./moon-stars";
import SVG_mortarboard from "./mortarboard";
import SVG_motherboard from "./motherboard";
import SVG_mouse from "./mouse";
import SVG_mouse2 from "./mouse2";
import SVG_mouse3 from "./mouse3";
import SVG_musicPlayer from "./music-player";
import SVG_nodeMinus from "./node-minus";
import SVG_nodePlus from "./node-plus";
import SVG_nut from "./nut";
import SVG_nvme from "./nvme";
import SVG_octagon from "./octagon";
import SVG_opticalAudio from "./optical-audio";
import SVG_pCircle from "./p-circle";
import SVG_pSquare from "./p-square";
import SVG_palette from "./palette";
import SVG_pass from "./pass";
import SVG_passport from "./passport";
import SVG_patchCheck from "./patch-check";
import SVG_patchExclamation from "./patch-exclamation";
import SVG_patchMinus from "./patch-minus";
import SVG_patchPlus from "./patch-plus";
import SVG_patchQuestion from "./patch-question";
import SVG_pauseBtn from "./pause-btn";
import SVG_pauseCircle from "./pause-circle";
import SVG_pause from "./pause";
import SVG_peace from "./peace";
import SVG_pen from "./pen";
import SVG_pencil from "./pencil";
import SVG_pentagon from "./pentagon";
import SVG_people from "./people";
import SVG_personBadge from "./person-badge";
import SVG_personCheck from "./person-check";
import SVG_personDash from "./person-dash";
import SVG_person from "./person";
import SVG_personLines from "./person-lines";
import SVG_personPlus from "./person-plus";
import SVG_personVcard from "./person-vcard";
import SVG_personX from "./person-x";
import SVG_phone from "./phone";
import SVG_phoneLandscape from "./phone-landscape";
import SVG_phoneVibrate from "./phone-vibrate";
import SVG_pieChart from "./pie-chart";
import SVG_piggyBank from "./piggy-bank";
import SVG_pinAngle from "./pin-angle";
import SVG_pin from "./pin";
import SVG_pinMap from "./pin-map";
import SVG_pip from "./pip";
import SVG_playBtn from "./play-btn";
import SVG_playCircle from "./play-circle";
import SVG_play from "./play";
import SVG_plug from "./plug";
import SVG_plusCircle from "./plus-circle";
import SVG_plusSquare from "./plus-square";
import SVG_postage from "./postage";
import SVG_postageHeart from "./postage-heart";
import SVG_postcard from "./postcard";
import SVG_postcardHeart from "./postcard-heart";
import SVG_printer from "./printer";
import SVG_projector from "./projector";
import SVG_puzzle from "./puzzle";
import SVG_questionCircle from "./question-circle";
import SVG_questionDiamond from "./question-diamond";
import SVG_questionOctagon from "./question-octagon";
import SVG_questionSquare from "./question-square";
import SVG_rCircle from "./r-circle";
import SVG_rSquare from "./r-square";
import SVG_recordBtn from "./record-btn";
import SVG_recordCircle from "./record-circle";
import SVG_record from "./record";
import SVG_record2 from "./record2";
import SVG_replyAll from "./reply-all";
import SVG_reply from "./reply";
import SVG_rewindBtn from "./rewind-btn";
import SVG_rewindCircle from "./rewind-circle";
import SVG_rewind from "./rewind";
import SVG_rocket from "./rocket";
import SVG_rocketTakeoff from "./rocket-takeoff";
import SVG_router from "./router";
import SVG_rss from "./rss";
import SVG_safe from "./safe";
import SVG_safe2 from "./safe2";
import SVG_save from "./save";
import SVG_save2 from "./save2";
import SVG_sdCard from "./sd-card";
import SVG_searchHeart from "./search-heart";
import SVG_sendArrowDown from "./send-arrow-down";
import SVG_sendArrowUp from "./send-arrow-up";
import SVG_sendCheck from "./send-check";
import SVG_sendDash from "./send-dash";
import SVG_sendExclamation from "./send-exclamation";
import SVG_send from "./send";
import SVG_sendPlus from "./send-plus";
import SVG_sendSlash from "./send-slash";
import SVG_sendX from "./send-x";
import SVG_share from "./share";
import SVG_shield from "./shield";
import SVG_shieldLock from "./shield-lock";
import SVG_shieldSlash from "./shield-slash";
import SVG_shift from "./shift";
import SVG_signDeadEnd from "./sign-dead-end";
import SVG_signDoNotEnter from "./sign-do-not-enter";
import SVG_signIntersection from "./sign-intersection";
import SVG_signIntersectionSide from "./sign-intersection-side";
import SVG_signIntersectionT from "./sign-intersection-t";
import SVG_signIntersectionY from "./sign-intersection-y";
import SVG_signMergeLeft from "./sign-merge-left";
import SVG_signMergeRight from "./sign-merge-right";
import SVG_signNoLeftTurn from "./sign-no-left-turn";
import SVG_signNoParking from "./sign-no-parking";
import SVG_signNoRightTurn from "./sign-no-right-turn";
import SVG_signRailroad from "./sign-railroad";
import SVG_signStop from "./sign-stop";
import SVG_signStopLights from "./sign-stop-lights";
import SVG_signTurnLeft from "./sign-turn-left";
import SVG_signTurnRight from "./sign-turn-right";
import SVG_signTurnSlightLeft from "./sign-turn-slight-left";
import SVG_signTurnSlightRight from "./sign-turn-slight-right";
import SVG_signYield from "./sign-yield";
import SVG_signpost2 from "./signpost-2";
import SVG_signpost from "./signpost";
import SVG_signpostSplit from "./signpost-split";
import SVG_sim from "./sim";
import SVG_simSlash from "./sim-slash";
import SVG_skipBackwardBtn from "./skip-backward-btn";
import SVG_skipBackwardCircle from "./skip-backward-circle";
import SVG_skipBackward from "./skip-backward";
import SVG_skipEndBtn from "./skip-end-btn";
import SVG_skipEndCircle from "./skip-end-circle";
import SVG_skipEnd from "./skip-end";
import SVG_skipForwardBtn from "./skip-forward-btn";
import SVG_skipForwardCircle from "./skip-forward-circle";
import SVG_skipForward from "./skip-forward";
import SVG_skipStartBtn from "./skip-start-btn";
import SVG_skipStartCircle from "./skip-start-circle";
import SVG_skipStart from "./skip-start";
import SVG_slashCircle from "./slash-circle";
import SVG_slashSquare from "./slash-square";
import SVG_speaker from "./speaker";
import SVG_square from "./square";
import SVG_star from "./star";
import SVG_stickies from "./stickies";
import SVG_sticky from "./sticky";
import SVG_stopBtn from "./stop-btn";
import SVG_stopCircle from "./stop-circle";
import SVG_stop from "./stop";
import SVG_stoplights from "./stoplights";
import SVG_stopwatch from "./stopwatch";
import SVG_suitClub from "./suit-club";
import SVG_suitDiamond from "./suit-diamond";
import SVG_suitHeart from "./suit-heart";
import SVG_suitSpade from "./suit-spade";
import SVG_suitcase from "./suitcase";
import SVG_suitcaseLg from "./suitcase-lg";
import SVG_suitcase2 from "./suitcase2";
import SVG_sun from "./sun";
import SVG_sunrise from "./sunrise";
import SVG_sunset from "./sunset";
import SVG_tablet from "./tablet";
import SVG_tabletLandscape from "./tablet-landscape";
import SVG_tag from "./tag";
import SVG_tags from "./tags";
import SVG_taxiFront from "./taxi-front";
import SVG_telephone from "./telephone";
import SVG_telephoneForward from "./telephone-forward";
import SVG_telephoneInbound from "./telephone-inbound";
import SVG_telephoneMinus from "./telephone-minus";
import SVG_telephoneOutbound from "./telephone-outbound";
import SVG_telephonePlus from "./telephone-plus";
import SVG_telephoneX from "./telephone-x";
import SVG_terminal from "./terminal";
import SVG_threads from "./threads";
import SVG_thunderbolt from "./thunderbolt";
import SVG_ticketDetailed from "./ticket-detailed";
import SVG_ticket from "./ticket";
import SVG_ticketPerforated from "./ticket-perforated";
import SVG_trainFreightFront from "./train-freight-front";
import SVG_trainFront from "./train-front";
import SVG_trainLightrailFront from "./train-lightrail-front";
import SVG_trash from "./trash";
import SVG_trash2 from "./trash2";
import SVG_trash3 from "./trash3";
import SVG_tree from "./tree";
import SVG_triangle from "./triangle";
import SVG_trophy from "./trophy";
import SVG_truckFront from "./truck-front";
import SVG_tv from "./tv";
import SVG_umbrella from "./umbrella";
import SVG_unlock from "./unlock";
import SVG_usbC from "./usb-c";
import SVG_usbDrive from "./usb-drive";
import SVG_usb from "./usb";
import SVG_usbMicro from "./usb-micro";
import SVG_usbMini from "./usb-mini";
import SVG_usbPlug from "./usb-plug";
import SVG_vinyl from "./vinyl";
import SVG_volumeDown from "./volume-down";
import SVG_volumeMute from "./volume-mute";
import SVG_volumeOff from "./volume-off";
import SVG_volumeUp from "./volume-up";
import SVG_wallet from "./wallet";
import SVG_webcam from "./webcam";
import SVG_wrenchAdjustableCircle from "./wrench-adjustable-circle";
import SVG_xCircle from "./x-circle";
import SVG_xDiamond from "./x-diamond";
import SVG_xOctagon from "./x-octagon";
import SVG_xSquare from "./x-square"

// map
const contentMap = {
"0-circle": SVG_0Circle,
"0-square": SVG_0Square,
"1-circle": SVG_1Circle,
"1-square": SVG_1Square,
"2-circle": SVG_2Circle,
"2-square": SVG_2Square,
"3-circle": SVG_3Circle,
"3-square": SVG_3Square,
"4-circle": SVG_4Circle,
"4-square": SVG_4Square,
"5-circle": SVG_5Circle,
"5-square": SVG_5Square,
"6-circle": SVG_6Circle,
"6-square": SVG_6Square,
"7-circle": SVG_7Circle,
"7-square": SVG_7Square,
"8-circle": SVG_8Circle,
"8-square": SVG_8Square,
"9-circle": SVG_9Circle,
"9-square": SVG_9Square,
"airplane-engines": SVG_airplaneEngines,
"airplane": SVG_airplane,
"alarm": SVG_alarm,
"archive": SVG_archive,
"arrow-down-circle": SVG_arrowDownCircle,
"arrow-down-left-circle": SVG_arrowDownLeftCircle,
"arrow-down-left-square": SVG_arrowDownLeftSquare,
"arrow-down-right-circle": SVG_arrowDownRightCircle,
"arrow-down-right-square": SVG_arrowDownRightSquare,
"arrow-down-square": SVG_arrowDownSquare,
"arrow-left-circle": SVG_arrowLeftCircle,
"arrow-left-square": SVG_arrowLeftSquare,
"arrow-right-circle": SVG_arrowRightCircle,
"arrow-right-square": SVG_arrowRightSquare,
"arrow-through-heart": SVG_arrowThroughHeart,
"arrow-up-circle": SVG_arrowUpCircle,
"arrow-up-left-circle": SVG_arrowUpLeftCircle,
"arrow-up-left-square": SVG_arrowUpLeftSquare,
"arrow-up-right-circle": SVG_arrowUpRightCircle,
"arrow-up-right-square": SVG_arrowUpRightSquare,
"arrow-up-square": SVG_arrowUpSquare,
"aspect-ratio": SVG_aspectRatio,
"award": SVG_award,
"backpack": SVG_backpack,
"backpack2": SVG_backpack2,
"backpack3": SVG_backpack3,
"backpack4": SVG_backpack4,
"backspace": SVG_backspace,
"backspace-reverse": SVG_backspaceReverse,
"badge-3d": SVG_badge3d,
"badge-4k": SVG_badge4k,
"badge-8k": SVG_badge8k,
"badge-ad": SVG_badgeAd,
"badge-ar": SVG_badgeAr,
"badge-cc": SVG_badgeCc,
"badge-hd": SVG_badgeHd,
"badge-sd": SVG_badgeSd,
"badge-tm": SVG_badgeTm,
"badge-vo": SVG_badgeVo,
"badge-vr": SVG_badgeVr,
"badge-wc": SVG_badgeWc,
"bag-check": SVG_bagCheck,
"bag-dash": SVG_bagDash,
"bag": SVG_bag,
"bag-heart": SVG_bagHeart,
"bag-plus": SVG_bagPlus,
"bag-x": SVG_bagX,
"balloon": SVG_balloon,
"balloon-heart": SVG_balloonHeart,
"ban": SVG_ban,
"bandaid": SVG_bandaid,
"bar-chart": SVG_barChart,
"bar-chart-line": SVG_barChartLine,
"basket": SVG_basket,
"basket2": SVG_basket2,
"basket3": SVG_basket3,
"bell": SVG_bell,
"bell-slash": SVG_bellSlash,
"binoculars": SVG_binoculars,
"book": SVG_book,
"bookmark-check": SVG_bookmarkCheck,
"bookmark-dash": SVG_bookmarkDash,
"bookmark": SVG_bookmark,
"bookmark-heart": SVG_bookmarkHeart,
"bookmark-plus": SVG_bookmarkPlus,
"bookmark-star": SVG_bookmarkStar,
"bookmark-x": SVG_bookmarkX,
"bookmarks": SVG_bookmarks,
"boombox": SVG_boombox,
"bootstrap": SVG_bootstrap,
"box": SVG_box,
"box-seam": SVG_boxSeam,
"box2": SVG_box2,
"box2-heart": SVG_box2Heart,
"briefcase": SVG_briefcase,
"brightness-alt-high": SVG_brightnessAltHigh,
"brightness-alt-low": SVG_brightnessAltLow,
"brightness-high": SVG_brightnessHigh,
"brightness-low": SVG_brightnessLow,
"brush": SVG_brush,
"bucket": SVG_bucket,
"bug": SVG_bug,
"building": SVG_building,
"buildings": SVG_buildings,
"bus-front": SVG_busFront,
"c-circle": SVG_cCircle,
"c-square": SVG_cSquare,
"cake": SVG_cake,
"cake2": SVG_cake2,
"calculator": SVG_calculator,
"calendar-check": SVG_calendarCheck,
"calendar-date": SVG_calendarDate,
"calendar-day": SVG_calendarDay,
"calendar-event": SVG_calendarEvent,
"calendar": SVG_calendar,
"calendar-heart": SVG_calendarHeart,
"calendar-minus": SVG_calendarMinus,
"calendar-month": SVG_calendarMonth,
"calendar-plus": SVG_calendarPlus,
"calendar-range": SVG_calendarRange,
"calendar-week": SVG_calendarWeek,
"calendar-x": SVG_calendarX,
"calendar2-check": SVG_calendar2Check,
"calendar2-date": SVG_calendar2Date,
"calendar2-day": SVG_calendar2Day,
"calendar2-event": SVG_calendar2Event,
"calendar2": SVG_calendar2,
"calendar2-heart": SVG_calendar2Heart,
"calendar2-minus": SVG_calendar2Minus,
"calendar2-month": SVG_calendar2Month,
"calendar2-plus": SVG_calendar2Plus,
"calendar2-range": SVG_calendar2Range,
"calendar2-week": SVG_calendar2Week,
"calendar2-x": SVG_calendar2X,
"calendar3-event": SVG_calendar3Event,
"calendar3": SVG_calendar3,
"calendar3-range": SVG_calendar3Range,
"calendar3-week": SVG_calendar3Week,
"camera": SVG_camera,
"camera-reels": SVG_cameraReels,
"camera-video": SVG_cameraVideo,
"camera-video-off": SVG_cameraVideoOff,
"capslock": SVG_capslock,
"car-front": SVG_carFront,
"caret-down": SVG_caretDown,
"caret-down-square": SVG_caretDownSquare,
"caret-left": SVG_caretLeft,
"caret-left-square": SVG_caretLeftSquare,
"caret-right": SVG_caretRight,
"caret-right-square": SVG_caretRightSquare,
"caret-up": SVG_caretUp,
"caret-up-square": SVG_caretUpSquare,
"cart-check": SVG_cartCheck,
"cart-dash": SVG_cartDash,
"cart": SVG_cart,
"cart-plus": SVG_cartPlus,
"cart-x": SVG_cartX,
"cassette": SVG_cassette,
"cc-circle": SVG_ccCircle,
"cc-square": SVG_ccSquare,
"chat-dots": SVG_chatDots,
"chat": SVG_chat,
"chat-heart": SVG_chatHeart,
"chat-left-dots": SVG_chatLeftDots,
"chat-left": SVG_chatLeft,
"chat-left-heart": SVG_chatLeftHeart,
"chat-left-quote": SVG_chatLeftQuote,
"chat-left-text": SVG_chatLeftText,
"chat-quote": SVG_chatQuote,
"chat-right-dots": SVG_chatRightDots,
"chat-right": SVG_chatRight,
"chat-right-heart": SVG_chatRightHeart,
"chat-right-quote": SVG_chatRightQuote,
"chat-right-text": SVG_chatRightText,
"chat-square-dots": SVG_chatSquareDots,
"chat-square": SVG_chatSquare,
"chat-square-heart": SVG_chatSquareHeart,
"chat-square-quote": SVG_chatSquareQuote,
"chat-square-text": SVG_chatSquareText,
"chat-text": SVG_chatText,
"check-circle": SVG_checkCircle,
"check-square": SVG_checkSquare,
"circle": SVG_circle,
"clipboard-check": SVG_clipboardCheck,
"clipboard-data": SVG_clipboardData,
"clipboard": SVG_clipboard,
"clipboard-heart": SVG_clipboardHeart,
"clipboard-minus": SVG_clipboardMinus,
"clipboard-plus": SVG_clipboardPlus,
"clipboard-x": SVG_clipboardX,
"clipboard2-check": SVG_clipboard2Check,
"clipboard2-data": SVG_clipboard2Data,
"clipboard2": SVG_clipboard2,
"clipboard2-heart": SVG_clipboard2Heart,
"clipboard2-minus": SVG_clipboard2Minus,
"clipboard2-plus": SVG_clipboard2Plus,
"clipboard2-pulse": SVG_clipboard2Pulse,
"clipboard2-x": SVG_clipboard2X,
"clock": SVG_clock,
"cloud-arrow-down": SVG_cloudArrowDown,
"cloud-arrow-up": SVG_cloudArrowUp,
"cloud-check": SVG_cloudCheck,
"cloud-download": SVG_cloudDownload,
"cloud-drizzle": SVG_cloudDrizzle,
"cloud": SVG_cloud,
"cloud-fog": SVG_cloudFog,
"cloud-fog2": SVG_cloudFog2,
"cloud-hail": SVG_cloudHail,
"cloud-haze": SVG_cloudHaze,
"cloud-haze2": SVG_cloudHaze2,
"cloud-lightning": SVG_cloudLightning,
"cloud-lightning-rain": SVG_cloudLightningRain,
"cloud-minus": SVG_cloudMinus,
"cloud-moon": SVG_cloudMoon,
"cloud-plus": SVG_cloudPlus,
"cloud-rain": SVG_cloudRain,
"cloud-rain-heavy": SVG_cloudRainHeavy,
"cloud-slash": SVG_cloudSlash,
"cloud-sleet": SVG_cloudSleet,
"cloud-snow": SVG_cloudSnow,
"cloud-sun": SVG_cloudSun,
"cloud-upload": SVG_cloudUpload,
"clouds": SVG_clouds,
"cloudy": SVG_cloudy,
"collection": SVG_collection,
"collection-play": SVG_collectionPlay,
"compass": SVG_compass,
"cpu": SVG_cpu,
"credit-card-2-back": SVG_creditCard2Back,
"credit-card-2-front": SVG_creditCard2Front,
"credit-card": SVG_creditCard,
"cup": SVG_cup,
"cup-hot": SVG_cupHot,
"cursor": SVG_cursor,
"dash-circle": SVG_dashCircle,
"dash-square": SVG_dashSquare,
"database": SVG_database,
"device-hdd": SVG_deviceHdd,
"device-ssd": SVG_deviceSsd,
"diagram-2": SVG_diagram2,
"diagram-3": SVG_diagram3,
"diamond": SVG_diamond,
"dice-1": SVG_dice1,
"dice-2": SVG_dice2,
"dice-3": SVG_dice3,
"dice-4": SVG_dice4,
"dice-5": SVG_dice5,
"dice-6": SVG_dice6,
"disc": SVG_disc,
"display": SVG_display,
"displayport": SVG_displayport,
"door-closed": SVG_doorClosed,
"door-open": SVG_doorOpen,
"dpad": SVG_dpad,
"droplet": SVG_droplet,
"duffle": SVG_duffle,
"ear": SVG_ear,
"easel": SVG_easel,
"easel2": SVG_easel2,
"easel3": SVG_easel3,
"egg": SVG_egg,
"eject": SVG_eject,
"emoji-angry": SVG_emojiAngry,
"emoji-astonished": SVG_emojiAstonished,
"emoji-dizzy": SVG_emojiDizzy,
"emoji-expressionless": SVG_emojiExpressionless,
"emoji-frown": SVG_emojiFrown,
"emoji-grimace": SVG_emojiGrimace,
"emoji-grin": SVG_emojiGrin,
"emoji-heart-eyes": SVG_emojiHeartEyes,
"emoji-kiss": SVG_emojiKiss,
"emoji-laughing": SVG_emojiLaughing,
"emoji-neutral": SVG_emojiNeutral,
"emoji-smile": SVG_emojiSmile,
"emoji-smile-upside-down": SVG_emojiSmileUpsideDown,
"emoji-sunglasses": SVG_emojiSunglasses,
"emoji-surprise": SVG_emojiSurprise,
"emoji-tear": SVG_emojiTear,
"emoji-wink": SVG_emojiWink,
"envelope-arrow-down": SVG_envelopeArrowDown,
"envelope-arrow-up": SVG_envelopeArrowUp,
"envelope-at": SVG_envelopeAt,
"envelope-check": SVG_envelopeCheck,
"envelope-dash": SVG_envelopeDash,
"envelope-exclamation": SVG_envelopeExclamation,
"envelope": SVG_envelope,
"envelope-heart": SVG_envelopeHeart,
"envelope-open": SVG_envelopeOpen,
"envelope-open-heart": SVG_envelopeOpenHeart,
"envelope-paper": SVG_envelopePaper,
"envelope-paper-heart": SVG_envelopePaperHeart,
"envelope-plus": SVG_envelopePlus,
"envelope-slash": SVG_envelopeSlash,
"envelope-x": SVG_envelopeX,
"eraser": SVG_eraser,
"ev-front": SVG_evFront,
"ev-station": SVG_evStation,
"exclamation-circle": SVG_exclamationCircle,
"exclamation-diamond": SVG_exclamationDiamond,
"exclamation-octagon": SVG_exclamationOctagon,
"exclamation-square": SVG_exclamationSquare,
"exclamation-triangle": SVG_exclamationTriangle,
"explicit": SVG_explicit,
"eye": SVG_eye,
"eye-slash": SVG_eyeSlash,
"fast-forward-btn": SVG_fastForwardBtn,
"fast-forward-circle": SVG_fastForwardCircle,
"fast-forward": SVG_fastForward,
"file-arrow-down": SVG_fileArrowDown,
"file-arrow-up": SVG_fileArrowUp,
"file-bar-graph": SVG_fileBarGraph,
"file-binary": SVG_fileBinary,
"file-break": SVG_fileBreak,
"file-check": SVG_fileCheck,
"file-code": SVG_fileCode,
"file-diff": SVG_fileDiff,
"file-earmark-arrow-down": SVG_fileEarmarkArrowDown,
"file-earmark-arrow-up": SVG_fileEarmarkArrowUp,
"file-earmark-bar-graph": SVG_fileEarmarkBarGraph,
"file-earmark-binary": SVG_fileEarmarkBinary,
"file-earmark-break": SVG_fileEarmarkBreak,
"file-earmark-check": SVG_fileEarmarkCheck,
"file-earmark-code": SVG_fileEarmarkCode,
"file-earmark-diff": SVG_fileEarmarkDiff,
"file-earmark-easel": SVG_fileEarmarkEasel,
"file-earmark-excel": SVG_fileEarmarkExcel,
"file-earmark": SVG_fileEarmark,
"file-earmark-font": SVG_fileEarmarkFont,
"file-earmark-image": SVG_fileEarmarkImage,
"file-earmark-lock": SVG_fileEarmarkLock,
"file-earmark-lock2": SVG_fileEarmarkLock2,
"file-earmark-medical": SVG_fileEarmarkMedical,
"file-earmark-minus": SVG_fileEarmarkMinus,
"file-earmark-music": SVG_fileEarmarkMusic,
"file-earmark-pdf": SVG_fileEarmarkPdf,
"file-earmark-person": SVG_fileEarmarkPerson,
"file-earmark-play": SVG_fileEarmarkPlay,
"file-earmark-plus": SVG_fileEarmarkPlus,
"file-earmark-post": SVG_fileEarmarkPost,
"file-earmark-ppt": SVG_fileEarmarkPpt,
"file-earmark-richtext": SVG_fileEarmarkRichtext,
"file-earmark-ruled": SVG_fileEarmarkRuled,
"file-earmark-slides": SVG_fileEarmarkSlides,
"file-earmark-spreadsheet": SVG_fileEarmarkSpreadsheet,
"file-earmark-text": SVG_fileEarmarkText,
"file-earmark-word": SVG_fileEarmarkWord,
"file-earmark-x": SVG_fileEarmarkX,
"file-earmark-zip": SVG_fileEarmarkZip,
"file-easel": SVG_fileEasel,
"file-excel": SVG_fileExcel,
"file": SVG_file,
"file-font": SVG_fileFont,
"file-image": SVG_fileImage,
"file-lock": SVG_fileLock,
"file-lock2": SVG_fileLock2,
"file-medical": SVG_fileMedical,
"file-minus": SVG_fileMinus,
"file-music": SVG_fileMusic,
"file-pdf": SVG_filePdf,
"file-person": SVG_filePerson,
"file-play": SVG_filePlay,
"file-plus": SVG_filePlus,
"file-post": SVG_filePost,
"file-ppt": SVG_filePpt,
"file-richtext": SVG_fileRichtext,
"file-ruled": SVG_fileRuled,
"file-slides": SVG_fileSlides,
"file-spreadsheet": SVG_fileSpreadsheet,
"file-text": SVG_fileText,
"file-word": SVG_fileWord,
"file-x": SVG_fileX,
"file-zip": SVG_fileZip,
"filter-circle": SVG_filterCircle,
"filter-square": SVG_filterSquare,
"flag": SVG_flag,
"floppy": SVG_floppy,
"floppy2": SVG_floppy2,
"folder": SVG_folder,
"folder-symlink": SVG_folderSymlink,
"forward": SVG_forward,
"fuel-pump-diesel": SVG_fuelPumpDiesel,
"fuel-pump": SVG_fuelPump,
"funnel": SVG_funnel,
"gear": SVG_gear,
"geo-alt": SVG_geoAlt,
"geo": SVG_geo,
"gift": SVG_gift,
"grid-1x2": SVG_grid1x2,
"grid-3x2-gap": SVG_grid3x2Gap,
"grid-3x3-gap": SVG_grid3x3Gap,
"grid": SVG_grid,
"h-circle": SVG_hCircle,
"h-square": SVG_hSquare,
"hand-index": SVG_handIndex,
"hand-index-thumb": SVG_handIndexThumb,
"hand-thumbs-down": SVG_handThumbsDown,
"hand-thumbs-up": SVG_handThumbsUp,
"handbag": SVG_handbag,
"hdd": SVG_hdd,
"hdd-network": SVG_hddNetwork,
"hdd-rack": SVG_hddRack,
"hdd-stack": SVG_hddStack,
"hdmi": SVG_hdmi,
"heart": SVG_heart,
"heart-pulse": SVG_heartPulse,
"heartbreak": SVG_heartbreak,
"heptagon": SVG_heptagon,
"hexagon": SVG_hexagon,
"hospital": SVG_hospital,
"house-add": SVG_houseAdd,
"house-check": SVG_houseCheck,
"house-dash": SVG_houseDash,
"house-door": SVG_houseDoor,
"house-down": SVG_houseDown,
"house-exclamation": SVG_houseExclamation,
"house": SVG_house,
"house-gear": SVG_houseGear,
"house-heart": SVG_houseHeart,
"house-lock": SVG_houseLock,
"house-slash": SVG_houseSlash,
"house-up": SVG_houseUp,
"house-x": SVG_houseX,
"houses": SVG_houses,
"image": SVG_image,
"inbox": SVG_inbox,
"inboxes": SVG_inboxes,
"info-circle": SVG_infoCircle,
"info-square": SVG_infoSquare,
"journal-bookmark": SVG_journalBookmark,
"kanban": SVG_kanban,
"key": SVG_key,
"keyboard": SVG_keyboard,
"lamp": SVG_lamp,
"laptop": SVG_laptop,
"layers": SVG_layers,
"lightbulb": SVG_lightbulb,
"lightbulb-off": SVG_lightbulbOff,
"lightning-charge": SVG_lightningCharge,
"lightning": SVG_lightning,
"lock": SVG_lock,
"luggage": SVG_luggage,
"lungs": SVG_lungs,
"magnet": SVG_magnet,
"map": SVG_map,
"markdown": SVG_markdown,
"megaphone": SVG_megaphone,
"menu-app": SVG_menuApp,
"menu-button": SVG_menuButton,
"menu-button-wide": SVG_menuButtonWide,
"mic": SVG_mic,
"mic-mute": SVG_micMute,
"modem": SVG_modem,
"moon": SVG_moon,
"moon-stars": SVG_moonStars,
"mortarboard": SVG_mortarboard,
"motherboard": SVG_motherboard,
"mouse": SVG_mouse,
"mouse2": SVG_mouse2,
"mouse3": SVG_mouse3,
"music-player": SVG_musicPlayer,
"node-minus": SVG_nodeMinus,
"node-plus": SVG_nodePlus,
"nut": SVG_nut,
"nvme": SVG_nvme,
"octagon": SVG_octagon,
"optical-audio": SVG_opticalAudio,
"p-circle": SVG_pCircle,
"p-square": SVG_pSquare,
"palette": SVG_palette,
"pass": SVG_pass,
"passport": SVG_passport,
"patch-check": SVG_patchCheck,
"patch-exclamation": SVG_patchExclamation,
"patch-minus": SVG_patchMinus,
"patch-plus": SVG_patchPlus,
"patch-question": SVG_patchQuestion,
"pause-btn": SVG_pauseBtn,
"pause-circle": SVG_pauseCircle,
"pause": SVG_pause,
"peace": SVG_peace,
"pen": SVG_pen,
"pencil": SVG_pencil,
"pentagon": SVG_pentagon,
"people": SVG_people,
"person-badge": SVG_personBadge,
"person-check": SVG_personCheck,
"person-dash": SVG_personDash,
"person": SVG_person,
"person-lines": SVG_personLines,
"person-plus": SVG_personPlus,
"person-vcard": SVG_personVcard,
"person-x": SVG_personX,
"phone": SVG_phone,
"phone-landscape": SVG_phoneLandscape,
"phone-vibrate": SVG_phoneVibrate,
"pie-chart": SVG_pieChart,
"piggy-bank": SVG_piggyBank,
"pin-angle": SVG_pinAngle,
"pin": SVG_pin,
"pin-map": SVG_pinMap,
"pip": SVG_pip,
"play-btn": SVG_playBtn,
"play-circle": SVG_playCircle,
"play": SVG_play,
"plug": SVG_plug,
"plus-circle": SVG_plusCircle,
"plus-square": SVG_plusSquare,
"postage": SVG_postage,
"postage-heart": SVG_postageHeart,
"postcard": SVG_postcard,
"postcard-heart": SVG_postcardHeart,
"printer": SVG_printer,
"projector": SVG_projector,
"puzzle": SVG_puzzle,
"question-circle": SVG_questionCircle,
"question-diamond": SVG_questionDiamond,
"question-octagon": SVG_questionOctagon,
"question-square": SVG_questionSquare,
"r-circle": SVG_rCircle,
"r-square": SVG_rSquare,
"record-btn": SVG_recordBtn,
"record-circle": SVG_recordCircle,
"record": SVG_record,
"record2": SVG_record2,
"reply-all": SVG_replyAll,
"reply": SVG_reply,
"rewind-btn": SVG_rewindBtn,
"rewind-circle": SVG_rewindCircle,
"rewind": SVG_rewind,
"rocket": SVG_rocket,
"rocket-takeoff": SVG_rocketTakeoff,
"router": SVG_router,
"rss": SVG_rss,
"safe": SVG_safe,
"safe2": SVG_safe2,
"save": SVG_save,
"save2": SVG_save2,
"sd-card": SVG_sdCard,
"search-heart": SVG_searchHeart,
"send-arrow-down": SVG_sendArrowDown,
"send-arrow-up": SVG_sendArrowUp,
"send-check": SVG_sendCheck,
"send-dash": SVG_sendDash,
"send-exclamation": SVG_sendExclamation,
"send": SVG_send,
"send-plus": SVG_sendPlus,
"send-slash": SVG_sendSlash,
"send-x": SVG_sendX,
"share": SVG_share,
"shield": SVG_shield,
"shield-lock": SVG_shieldLock,
"shield-slash": SVG_shieldSlash,
"shift": SVG_shift,
"sign-dead-end": SVG_signDeadEnd,
"sign-do-not-enter": SVG_signDoNotEnter,
"sign-intersection": SVG_signIntersection,
"sign-intersection-side": SVG_signIntersectionSide,
"sign-intersection-t": SVG_signIntersectionT,
"sign-intersection-y": SVG_signIntersectionY,
"sign-merge-left": SVG_signMergeLeft,
"sign-merge-right": SVG_signMergeRight,
"sign-no-left-turn": SVG_signNoLeftTurn,
"sign-no-parking": SVG_signNoParking,
"sign-no-right-turn": SVG_signNoRightTurn,
"sign-railroad": SVG_signRailroad,
"sign-stop": SVG_signStop,
"sign-stop-lights": SVG_signStopLights,
"sign-turn-left": SVG_signTurnLeft,
"sign-turn-right": SVG_signTurnRight,
"sign-turn-slight-left": SVG_signTurnSlightLeft,
"sign-turn-slight-right": SVG_signTurnSlightRight,
"sign-yield": SVG_signYield,
"signpost-2": SVG_signpost2,
"signpost": SVG_signpost,
"signpost-split": SVG_signpostSplit,
"sim": SVG_sim,
"sim-slash": SVG_simSlash,
"skip-backward-btn": SVG_skipBackwardBtn,
"skip-backward-circle": SVG_skipBackwardCircle,
"skip-backward": SVG_skipBackward,
"skip-end-btn": SVG_skipEndBtn,
"skip-end-circle": SVG_skipEndCircle,
"skip-end": SVG_skipEnd,
"skip-forward-btn": SVG_skipForwardBtn,
"skip-forward-circle": SVG_skipForwardCircle,
"skip-forward": SVG_skipForward,
"skip-start-btn": SVG_skipStartBtn,
"skip-start-circle": SVG_skipStartCircle,
"skip-start": SVG_skipStart,
"slash-circle": SVG_slashCircle,
"slash-square": SVG_slashSquare,
"speaker": SVG_speaker,
"square": SVG_square,
"star": SVG_star,
"stickies": SVG_stickies,
"sticky": SVG_sticky,
"stop-btn": SVG_stopBtn,
"stop-circle": SVG_stopCircle,
"stop": SVG_stop,
"stoplights": SVG_stoplights,
"stopwatch": SVG_stopwatch,
"suit-club": SVG_suitClub,
"suit-diamond": SVG_suitDiamond,
"suit-heart": SVG_suitHeart,
"suit-spade": SVG_suitSpade,
"suitcase": SVG_suitcase,
"suitcase-lg": SVG_suitcaseLg,
"suitcase2": SVG_suitcase2,
"sun": SVG_sun,
"sunrise": SVG_sunrise,
"sunset": SVG_sunset,
"tablet": SVG_tablet,
"tablet-landscape": SVG_tabletLandscape,
"tag": SVG_tag,
"tags": SVG_tags,
"taxi-front": SVG_taxiFront,
"telephone": SVG_telephone,
"telephone-forward": SVG_telephoneForward,
"telephone-inbound": SVG_telephoneInbound,
"telephone-minus": SVG_telephoneMinus,
"telephone-outbound": SVG_telephoneOutbound,
"telephone-plus": SVG_telephonePlus,
"telephone-x": SVG_telephoneX,
"terminal": SVG_terminal,
"threads": SVG_threads,
"thunderbolt": SVG_thunderbolt,
"ticket-detailed": SVG_ticketDetailed,
"ticket": SVG_ticket,
"ticket-perforated": SVG_ticketPerforated,
"train-freight-front": SVG_trainFreightFront,
"train-front": SVG_trainFront,
"train-lightrail-front": SVG_trainLightrailFront,
"trash": SVG_trash,
"trash2": SVG_trash2,
"trash3": SVG_trash3,
"tree": SVG_tree,
"triangle": SVG_triangle,
"trophy": SVG_trophy,
"truck-front": SVG_truckFront,
"tv": SVG_tv,
"umbrella": SVG_umbrella,
"unlock": SVG_unlock,
"usb-c": SVG_usbC,
"usb-drive": SVG_usbDrive,
"usb": SVG_usb,
"usb-micro": SVG_usbMicro,
"usb-mini": SVG_usbMini,
"usb-plug": SVG_usbPlug,
"vinyl": SVG_vinyl,
"volume-down": SVG_volumeDown,
"volume-mute": SVG_volumeMute,
"volume-off": SVG_volumeOff,
"volume-up": SVG_volumeUp,
"wallet": SVG_wallet,
"webcam": SVG_webcam,
"wrench-adjustable-circle": SVG_wrenchAdjustableCircle,
"x-circle": SVG_xCircle,
"x-diamond": SVG_xDiamond,
"x-octagon": SVG_xOctagon,
"x-square": SVG_xSquare
};

// types
export type IconNames = keyof typeof contentMap;

// iconNames
export const iconNames: IconNames[] = Object.keys(contentMap) as IconNames[];

export const map: IconsMapType<IconNames> = contentMap;
