# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Packages release
run-name: Beta release ${{github.event.inputs.cbPackage}} with ${{github.event.inputs.cbVersionChange}} version change
concurrency:
  group: 'svgr-iconkit-cicd-release-${{github.event.inputs.cbPackage}}-${{github.event.inputs.cbVersionChange}}'
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      cbVersionChange:
        type: choice 
        required: true
        description: The type of version change
        default: "patch"
        options:
        - "no"
        - "patch"
        - "minor"
        - "major"
      cbPackage:
        type: choice 
        required: true
        description: Package to be publish
        default: "all"
        options:
        - "all"
        - "packages/core"
        - "packages/ext-ant-design"
        - "packages/ext-bootstrap"
        - "packages/ext-css-gg"
        - "packages/ext-entypo"
        - "packages/ext-evil-icons"
        - "packages/ext-feather"
        - "packages/ext-flag-icons"
        - "packages/ext-flat-color-icons"
        - "packages/ext-fluentui-system"
        - "packages/ext-fontawesome"
        - "packages/ext-fontawesome-brands"
        - "packages/ext-fontawesome5"
        - "packages/ext-fontawesome5-brands"
        - "packages/ext-fontisto"
        - "packages/ext-foundation"
        - "packages/ext-grommet-icons"
        - "packages/ext-heroicons"
        - "packages/ext-ionicons"
        - "packages/ext-material-community"
        - "packages/ext-material-design"
        - "packages/ext-octicons"
        - "packages/ext-primeicons"
        - "packages/ext-remixicons"
        - "packages/ext-simple-icons"
        - "packages/ext-simple-line-icons"
        - "packages/ext-tabler-icons"
        - "packages/ext-themify-icons"
        - "packages/ext-typicons"
        - "packages/ext-weather-icons"
        - "packages/ext-xnix"
        - "tools/common-utils"
        - "tools/build-config"
        - "tools/build-utils"
        - "tools/cli"
        - "tools/generator-iconkit"
      cGithubPackagesPublish:
        type: choice 
        required: true
        description: Require publish to github registry?
        default: "yes"
        options:
        - "no"
        - "yes"
      cNpmPublish:
        type: choice 
        required: true
        description: Require publish to npm registry?
        default: "yes"
        options:
        - "no"
        - "yes"
      cbDebug:
        type: choice 
        required: true
        description: Debug mode?
        default: "no"
        options:
        - "no"
        - "yes"


permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Install all packages
        if: github.event.inputs.cbPackage == 'all'
        run: |
          yarn config set disable-self-update-check true
          yarn config set ignore-engines true
          yarn config list
          yarn install
      - name: Install target package
        if: github.event.inputs.cbPackage != 'all'
        working-directory: ${{ github.event.inputs.cbPackage }}
        run: |
          cat ../../package.json
          mv ../../package.json ../../package.tmp.json
          npm install --legacy-peer-deps
          mv ../../package.tmp.json ../../package.json
      - name: 'Upload target package packages'
        if: github.event.inputs.cbPackage != 'all' && github.event.inputs.cbDebug == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: release-beta-install
          path: ${{ github.event.inputs.cbPackage }}
          retention-days: 14
      - name: Bump version to all
        if: github.event.inputs.cbPackage == 'all' && github.event.inputs.cbVersionChange != 'no'
        run: |
          yarn version:beta --yes --no-push
          git status
          git add ./
      - name: Bump version to target package
        if: github.event.inputs.cbPackage != 'all' && github.event.inputs.cbVersionChange != 'no'
        working-directory: ${{ github.event.inputs.cbPackage }}
        run: |
          OLD_VERSION=$(node -e "console.log(require('./package.json').version)")
          yarn version --${{ github.event.inputs.cbVersionChange }} --preid beta --yes --no-push
          NEW_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "Package version changed." >> $GITHUB_STEP_SUMMARY
          echo "Old version: $OLD_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "New version: $NEW_VERSION" >> $GITHUB_STEP_SUMMARY
          git status
          git add ./
      - name: Build all
        if: github.event.inputs.cbPackage == 'all'
        run: |
          yarn run build
      - name: Build to target package
        if: github.event.inputs.cbPackage != 'all'
        working-directory: ${{ github.event.inputs.cbPackage }}
        run: |
          ls -al
          npm run build
      - name: 'Upload target package artifact'
        if: github.event.inputs.cbPackage != 'all' && github.event.inputs.cbDebug == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: release-beta-build
          path: ${{ github.event.inputs.cbPackage }}
          retention-days: 14
      - name: publish all to registry(github)
        if: github.event.inputs.cbPackage == 'all' && github.event.inputs.cGithubPackagesPublish == 'yes'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish:all:github
      - name: publish target package to registry(github)
        if: github.event.inputs.cbPackage != 'all' && github.event.inputs.cGithubPackagesPublish == 'yes'
        working-directory: ${{ github.event.inputs.cbPackage }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish --access public --non-interactive  --no-git-tag-version  --registry=https://npm.pkg.github.com/
      - name: publish all to registry(npmjs.com)
        if: github.event.inputs.cbPackage == 'all' && github.event.inputs.cNpmPublish == 'yes'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish:all --registry=https://registry.npmjs.org/
      - name: publish target package to registry(npmjs.com)
        if: github.event.inputs.cbPackage != 'all' && github.event.inputs.cNpmPublish == 'yes'
        working-directory: ${{ github.event.inputs.cbPackage }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish --access public --non-interactive  --no-git-tag-version --registry=https://registry.npmjs.org/
      - name: push result
        run: |
          git status
          git pull --rebase -f
          git push --verbose
          echo "Package changes pushed." >> $GITHUB_STEP_SUMMARY
